# this section can include any options available to mail gem's SMTP config
:smtp:
  :address: "smtp.gmail.com"
  :port: 587
  :user_name: "user@gmail.com"
  :password: "1234567890"
  :authentication: "plain"
  :enable_starttls_auto: true

:mail:
  :from: "user@gmail.com"
  :to:
    - "user@non-gmail.com"
    - "user@gmail.com"
